import type { User, AttendanceRecord, FacultyAttendance, Assignment, Exam, Notification, Department, AcademicSession, Class } from "./types"

export const mockUsers: User[] = [
  { id: "A001", name: "Dr. Sarah Wilson", email: "sarah.wilson@university.edu", role: "admin", department: "Administration", phone: "+1-555-0100", join_date: "2020-08-15", status: "active" },
  { id: "F001", name: "Prof. James Carter", email: "james.carter@university.edu", role: "faculty", department: "Computer Science", phone: "+1-555-0201", join_date: "2021-01-10", status: "active" },
  { id: "F002", name: "Dr. Emily Chen", email: "emily.chen@university.edu", role: "faculty", department: "Mathematics", phone: "+1-555-0202", join_date: "2021-06-20", status: "active" },
  { id: "F003", name: "Prof. Robert Davis", email: "robert.davis@university.edu", role: "faculty", department: "Physics", phone: "+1-555-0203", join_date: "2022-01-05", status: "active" },
  { id: "F004", name: "Dr. Lisa Wang", email: "lisa.wang@university.edu", role: "faculty", department: "Computer Science", phone: "+1-555-0204", join_date: "2023-08-15", status: "active" },
  { id: "S001", name: "Alex Thompson", email: "alex.t@student.edu", role: "student", department: "Computer Science", class: "CS-301", phone: "+1-555-0301", join_date: "2024-08-20", status: "active" },
  { id: "S002", name: "Maria Garcia", email: "maria.g@student.edu", role: "student", department: "Computer Science", class: "CS-301", phone: "+1-555-0302", join_date: "2024-08-20", status: "active" },
  { id: "S003", name: "Ryan Patel", email: "ryan.p@student.edu", role: "student", department: "Computer Science", class: "CS-301", phone: "+1-555-0303", join_date: "2024-08-20", status: "active" },
  { id: "S004", name: "Sophie Lee", email: "sophie.l@student.edu", role: "student", department: "Mathematics", class: "MA-201", phone: "+1-555-0304", join_date: "2024-08-20", status: "active" },
  { id: "S005", name: "David Kim", email: "david.k@student.edu", role: "student", department: "Computer Science", class: "CS-301", phone: "+1-555-0305", join_date: "2024-08-20", status: "active" },
  { id: "S006", name: "Emma Brown", email: "emma.b@student.edu", role: "student", department: "Mathematics", class: "MA-201", phone: "+1-555-0306", join_date: "2024-08-20", status: "active" },
  { id: "S007", name: "James Wilson", email: "james.w@student.edu", role: "student", department: "Physics", class: "PH-101", phone: "+1-555-0307", join_date: "2024-08-20", status: "active" },
  { id: "S008", name: "Olivia Martinez", email: "olivia.m@student.edu", role: "student", department: "Computer Science", class: "CS-302", phone: "+1-555-0308", join_date: "2024-08-20", status: "inactive" },
]

export const mockAttendance: AttendanceRecord[] = [
  {
    id: "AT001",
    student_id: "S001",
    student_name: "Alex Thompson",
    date: "2026-02-09",
    status: "present",
    subject_id: "SUB001",
    subject_name: "Data Structures",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "face-recognition",
    created_at: "2026-02-09T09:10:00",
  },
  {
    id: "AT002",
    student_id: "S002",
    student_name: "Maria Garcia",
    date: "2026-02-09",
    status: "present",
    subject_id: "SUB001",
    subject_name: "Data Structures",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "face-recognition",
    created_at: "2026-02-09T09:12:00",
  },
  {
    id: "AT003",
    student_id: "S003",
    student_name: "Ryan Patel",
    date: "2026-02-09",
    status: "absent",
    subject_id: "SUB001",
    subject_name: "Data Structures",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "manual",
    created_at: "2026-02-09T09:20:00",
  },
  {
    id: "AT004",
    student_id: "S004",
    student_name: "Sophie Lee",
    date: "2026-02-09",
    status: "present",
    subject_id: "SUB002",
    subject_name: "Linear Algebra",
    marked_by: "F002",
    marked_name: "Prof. Emily Davis",
    method: "face-recognition",
    created_at: "2026-02-09T10:00:00",
  },
  {
    id: "AT005",
    student_id: "S005",
    student_name: "David Kim",
    date: "2026-02-12",
    status: "late",
    subject_id: "SUB001",
    subject_name: "Data Structures",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "self-marked",
    created_at: "2026-02-12T09:05:00",
  },
  {
    id: "AT006",
    student_id: "S006",
    student_name: "Emma Brown",
    date: "2026-02-12",
    status: "present",
    subject_id: "SUB002",
    subject_name: "Linear Algebra",
    marked_by: "F002",
    marked_name: "Prof. Emily Davis",
    method: "face-recognition",
    created_at: "2026-02-12T10:02:00",
  },
  {
    id: "AT007",
    student_id: "S001",
    student_name: "Alex Thompson",
    date: "2026-02-12",
    status: "present",
    subject_id: "SUB003",
    subject_name: "Algorithms",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "face-recognition",
    created_at: "2026-02-12T11:00:00",
  },
  {
    id: "AT008",
    student_id: "S002",
    student_name: "Maria Garcia",
    date: "2026-02-12",
    status: "absent",
    subject_id: "SUB003",
    subject_name: "Algorithms",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "manual",
    created_at: "2026-02-12T11:05:00",
  },
  {
    id: "AT009",
    student_id: "S003",
    student_name: "Ryan Patel",
    date: "2026-02-11",
    status: "present",
    subject_id: "SUB003",
    subject_name: "Algorithms",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "self-marked",
    created_at: "2026-02-11T11:00:00",
  },
  {
    id: "AT010",
    student_id: "S005",
    student_name: "David Kim",
    date: "2026-02-11",
    status: "present",
    subject_id: "SUB003",
    subject_name: "Algorithms",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "face-recognition",
    created_at: "2026-02-11T11:02:00",
  },
  {
    id: "AT011",
    student_id: "S001",
    student_name: "Alex Thompson",
    date: "2026-02-04",
    status: "present",
    subject_id: "SUB001",
    subject_name: "Data Structures",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "face-recognition",
    created_at: "2026-02-04T09:00:00",
  },
  {
    id: "AT012",
    student_id: "S002",
    student_name: "Maria Garcia",
    date: "2026-02-04",
    status: "present",
    subject_id: "SUB001",
    subject_name: "Data Structures",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "face-recognition",
    created_at: "2026-02-04T09:02:00",
  },
  {
    id: "AT013",
    student_id: "S003",
    student_name: "Ryan Patel",
    date: "2026-02-04",
    status: "present",
    subject_id: "SUB001",
    subject_name: "Data Structures",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "self-marked",
    created_at: "2026-02-04T09:03:00",
  },
  {
    id: "AT014",
    student_id: "S005",
    student_name: "David Kim",
    date: "2026-02-04",
    status: "absent",
    subject_id: "SUB001",
    subject_name: "Data Structures",
    marked_by: "F001",
    marked_name: "Dr. John Smith",
    method: "manual",
    created_at: "2026-02-04T09:05:00",
  },
];

export const mockFacultyAttendance: FacultyAttendance[] = [
  { id: "FA001", faculty_id: "F001", faculty_name: "Prof. James Carter", date: "2026-02-06", check_in: "08:45 AM", check_out: "05:10 PM", status: "present", verify_by_id: "A001", verification_status: "approved" },
  { id: "FA002", faculty_id: "F002", faculty_name: "Dr. Emily Chen", date: "2026-02-06", check_in: "09:02 AM", check_out: "04:55 PM", status: "present", verify_by_id: "A001", verification_status: "approved" },
  { id: "FA003", faculty_id: "F003", faculty_name: "Prof. Robert Davis", date: "2026-02-06", check_in: "09:20 AM", status: "late", verification_status: "pending", remarks: "Traffic delay" },
  { id: "FA004", faculty_id: "F004", faculty_name: "Dr. Lisa Wang", date: "2026-02-06", check_in: "", status: "on-leave", verification_status: "approved", verify_by_id: "A001", remarks: "Medical leave" },
  { id: "FA005", faculty_id: "F001", faculty_name: "Prof. James Carter", date: "2026-02-05", check_in: "08:30 AM", check_out: "05:00 PM", status: "present", verify_by_id: "A001", verification_status: "approved" },
  { id: "FA006", faculty_id: "F002", faculty_name: "Dr. Emily Chen", date: "2026-02-05", check_in: "08:55 AM", check_out: "05:05 PM", status: "present", verify_by_id: "A001", verification_status: "approved" },
  { id: "FA007", faculty_id: "F003", faculty_name: "Prof. Robert Davis", date: "2026-02-05", check_in: "08:40 AM", check_out: "04:50 PM", status: "present", verification_status: "pending" },
  { id: "FA008", faculty_id: "F004", faculty_name: "Dr. Lisa Wang", date: "2026-02-05", check_in: "09:00 AM", check_out: "05:00 PM", status: "present", verification_status: "pending" },
  { id: "FA009", faculty_id: "F001", faculty_name: "Prof. James Carter", date: "2026-02-04", check_in: "08:50 AM", check_out: "05:15 PM", status: "present", verify_by_id: "A001", verification_status: "approved" },
  { id: "FA010", faculty_id: "F002", faculty_name: "Dr. Emily Chen", date: "2026-02-04", check_in: "", status: "absent", verification_status: "approved", verify_by_id: "A001", remarks: "Sick leave" },
]

export const mockDepartments: Department[] = [
  { id: "D001", name: "Computer Science", head_id: "Prof. James Carter", student_count: 45, faculty_count: 2 },
  { id: "D002", name: "Mathematics", head_id: "Dr. Emily Chen", student_count: 32, faculty_count: 1 },
  { id: "D003", name: "Physics", head_id: "Prof. Robert Davis", student_count: 28, faculty_count: 1 },
]

export const mockSessions: AcademicSession[] = [
  {
    id: "SES001",
    name: "Spring 2026",
    start_date: "2026-01-15",
    end_date: "2026-05-30",
    student_count: "120",
    status: "active",
  },
  {
    id: "SES002",
    name: "Fall 2026",
    start_date: "2026-08-20",
    end_date: "2026-12-15",
    student_count: "150",
    status: "upcoming",
  },
  {
    id: "SES003",
    name: "Fall 2025",
    start_date: "2025-08-20",
    end_date: "2025-12-15",
    student_count: "135",
    status: "completed",
  },
];

export const mockAssignments: Assignment[] = [
  { id: "AS001", title: "Binary Tree Implementation", subject: "Data Structures", dueDate: "2026-02-15", description: "Implement a balanced binary search tree with insert, delete, and search operations.", status: "pending", createdBy: "F001" },
  { id: "AS002", title: "Sorting Algorithm Analysis", subject: "Algorithms", dueDate: "2026-02-20", description: "Compare time complexity of quicksort, mergesort, and heapsort with benchmarks.", status: "pending", createdBy: "F001" },
  { id: "AS003", title: "Matrix Operations", subject: "Linear Algebra", dueDate: "2026-02-12", description: "Solve the given system of linear equations using Gaussian elimination.", status: "submitted", createdBy: "F002" },
  { id: "AS004", title: "Graph Traversal", subject: "Data Structures", dueDate: "2026-02-25", description: "Implement BFS and DFS and demonstrate on a given graph.", status: "pending", createdBy: "F001" },
]

export const mockExams: Exam[] = [
  { id: "E001", subject: "Data Structures", date: "2026-03-10", time: "09:00 AM", venue: "Hall A", type: "Mid-term" },
  { id: "E002", subject: "Algorithms", date: "2026-03-12", time: "02:00 PM", venue: "Hall B", type: "Mid-term" },
  { id: "E003", subject: "Linear Algebra", date: "2026-03-14", time: "09:00 AM", venue: "Hall C", type: "Mid-term" },
  { id: "E004", subject: "Data Structures", date: "2026-05-20", time: "09:00 AM", venue: "Hall A", type: "Final" },
]

export const mockNotifications: Notification[] = [
  { id: "N001", title: "Mid-term Schedule Released", message: "The mid-term examination schedule for Spring 2026 has been published.", category: "exam", read: false, timestamp: "2026-02-06T10:00:00Z" },
  { id: "N002", title: "Assignment Due Reminder", message: "Binary Tree Implementation is due on Feb 15, 2026.", category: "assignment", read: false, timestamp: "2026-02-06T08:30:00Z" },
  { id: "N003", title: "Campus Holiday Notice", message: "The campus will be closed on Feb 17 for Presidents' Day.", category: "announcement", read: true, timestamp: "2026-02-05T14:00:00Z" },
  { id: "N004", title: "New Assignment Posted", message: "Graph Traversal assignment has been posted for Data Structures.", category: "assignment", read: false, timestamp: "2026-02-05T09:00:00Z" },
  { id: "N005", title: "Lab Session Rescheduled", message: "Friday's lab session has been moved to Saturday 10 AM.", category: "announcement", read: true, timestamp: "2026-02-04T16:00:00Z" },
  { id: "N006", title: "Attendance Marked", message: "Your attendance for Data Structures on Feb 6 has been recorded.", category: "attendance", read: false, timestamp: "2026-02-06T09:15:00Z" },
]

export const mockClasses: Class[] = [
  {
    id: "C101",
    name: "B.Tech 1st Year - A",
    class_teacher_id: "U101",
    class_teacher: "Dr. Rahul Sharma",
    dept_id: "D01",
    dept_name: "Computer Science",
    student_count: "62",
    created_at: "2026-01-10T09:30:00Z",
    create_bu: "admin01",
  },
  {
    id: "C102",
    name: "B.Tech 1st Year - B",
    class_teacher_id: "U102",
    class_teacher: "Prof. Anjali Mehta",
    dept_id: "D01",
    dept_name: "Computer Science",
    student_count: "58",
    created_at: "2026-01-10T10:00:00Z",
    create_bu: "admin01",
  },
  {
    id: "C201",
    name: "B.Tech 2nd Year - A",
    class_teacher_id: "U103",
    class_teacher: "Dr. Vikram Singh",
    dept_id: "D02",
    dept_name: "Information Technology",
    student_count: "55",
    created_at: "2026-01-12T08:45:00Z",
    create_bu: "admin02",
  },
  {
    id: "C202",
    name: "B.Tech 2nd Year - B",
    class_teacher_id: "U104",
    class_teacher: "Prof. Neha Kapoor",
    dept_id: "D02",
    dept_name: "Information Technology",
    student_count: "60",
    created_at: "2026-01-12T09:15:00Z",
    create_bu: "admin02",
  },
  {
    id: "C301",
    name: "B.Tech 3rd Year - A",
    class_teacher_id: "U105",
    class_teacher: "Dr. Arjun Verma",
    dept_id: "D03",
    dept_name: "Electronics",
    student_count: "48",
    created_at: "2026-01-15T11:00:00Z",
    create_bu: "admin03",
  },
  {
    id: "C302",
    name: "B.Tech 3rd Year - B",
    class_teacher_id: "U106",
    class_teacher: "Prof. Sneha Iyer",
    dept_id: "D03",
    dept_name: "Electronics",
    student_count: "52",
    created_at: "2026-01-15T11:30:00Z",
    create_bu: "admin03",
  },
  {
    id: "C401",
    name: "B.Tech 4th Year - A",
    class_teacher_id: "U107",
    class_teacher: "Dr. Manish Gupta",
    dept_id: "D01",
    dept_name: "Computer Science",
    student_count: "44",
    created_at: "2026-01-18T09:00:00Z",
    create_bu: "admin01",
  },
  {
    id: "C501",
    name: "M.Tech 1st Year - A",
    class_teacher_id: "U108",
    class_teacher: "Prof. Kavita Rao",
    dept_id: "D04",
    dept_name: "Mechanical Engineering",
    student_count: "28",
    created_at: "2026-01-20T10:15:00Z",
    create_bu: "admin04",
  },
]



export const weeklyAttendanceData = [
  { day: "Mon", present: 42, absent: 8 },
  { day: "Tue", present: 45, absent: 5 },
  { day: "Wed", present: 38, absent: 12 },
  { day: "Thu", present: 44, absent: 6 },
  { day: "Fri", present: 40, absent: 10 },
]

export const monthlyAttendanceData = [
  { month: "Sep", percentage: 92 },
  { month: "Oct", percentage: 88 },
  { month: "Nov", percentage: 90 },
  { month: "Dec", percentage: 85 },
  { month: "Jan", percentage: 91 },
  { month: "Feb", percentage: 89 },
]

export const subjectAttendanceData = [
  { subject: "Data Structures", percentage: 88 },
  { subject: "Algorithms", percentage: 92 },
  { subject: "Linear Algebra", percentage: 85 },
  { subject: "Databases", percentage: 90 },
]